//! Compiles the browser interface into the binary, so the page and the program a
//! researcher copies onto a machine are one file.
//!
//! `web/pkg/` is a build artefact and version control excludes it, so a fresh clone has no
//! WebAssembly module to embed. This script embeds it when it is there and embeds an empty
//! set when it is not. Failing here instead would fail `cargo test --workspace`, which the
//! browser publication workflow runs before it builds the bundle, and every contributor's
//! first `cargo build`. The gate that refuses a shipped binary carrying no module lives on
//! the release, in `scripts/verify-release-artefacts.sh`.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

include!("src/content_types.rs");

/// Repository documentation that sits beside the interface without being part of it.
/// Serving it would put a build instruction on a port somebody opened to analyse a trial.
/// The name travels into the binary so the test that compares the embedded set against the
/// directory subtracts what was excluded on purpose rather than counting to a number, and a
/// sixth interface file added later fails that test instead of being dropped the same way.
const NOT_PART_OF_THE_INTERFACE: &[&str] = &["README.md"];

/// The one subdirectory of `web/` the interface is allowed to have. Anything else is a set
/// of files this script would drop without saying so.
const BROWSER_BUNDLE_DIRECTORY: &str = "pkg";

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // Absolute, from the manifest directory. A build script's working directory is the
    // crate root, so a literal `web/pkg` would name a path inside this crate that never
    // exists, and the binary would never rebuild when the real one appeared.
    let web = std::fs::canonicalize(manifest.join("../../web"))
        .unwrap_or_else(|error| panic!("cannot read the browser interface directory: {error}"));
    let bundle = web.join(BROWSER_BUNDLE_DIRECTORY);

    let interface = interface_files(&web);
    let bundle_files = if bundle.is_dir() {
        files_in(&bundle)
    } else {
        Vec::new()
    };

    for path in watched_paths(&web, &bundle, &interface, &bundle_files) {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let mut entries = Vec::new();
    for file in &interface {
        entries.push(entry(file.file_name().unwrap().to_str().unwrap(), file));
    }
    for file in &bundle_files {
        let name = file.file_name().unwrap().to_str().unwrap();
        entries.push(entry(&format!("{BROWSER_BUNDLE_DIRECTORY}/{name}"), file));
    }

    let mut generated = String::from(
        "// Generated by build.rs. The browser interface travels inside the binary.\n\
         pub static EMBEDDED_ASSETS: &[Asset] = &[\n",
    );
    for line in &entries {
        generated.push_str(line);
    }
    generated.push_str("];\n\n");
    generated.push_str(&format!(
        "pub static NOT_PART_OF_THE_INTERFACE: &[&str] = &{NOT_PART_OF_THE_INTERFACE:?};\n\n\
         pub static THE_BROWSER_BUNDLE_WAS_BUILT: bool = {};\n",
        bundle.is_dir()
    ));

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_assets.rs");
    std::fs::write(out, generated).unwrap();
}

/// The files the page loads, which is every file directly in `web/` that the exclusion list
/// does not name. A directory other than the browser bundle is refused rather than skipped,
/// because a set of assets silently dropped is the failure this crate's test exists to
/// catch one layer down.
fn interface_files(web: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    for entry in std::fs::read_dir(web).unwrap() {
        let entry = entry.unwrap();
        let name = entry.file_name().to_string_lossy().into_owned();
        if entry.path().is_dir() {
            assert!(
                name == BROWSER_BUNDLE_DIRECTORY,
                "web/{name} is a directory this build script has no rule for; \
                 either add it to the interface or say why it is excluded"
            );
            continue;
        }
        if NOT_PART_OF_THE_INTERFACE.contains(&name.as_str()) {
            continue;
        }
        files.push(entry.path());
    }
    files.sort();
    files
}

fn files_in(directory: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(directory)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.is_file())
        .collect();
    files.sort();
    files
}

/// One generated `Asset`, with the content type resolved here so the server never holds an
/// absent one. Text goes in through `include_str!`, which is what makes the `charset=utf-8`
/// in the header a checked claim rather than a stated one.
fn entry(served_as: &str, file: &Path) -> String {
    let Some(content_type) = content_type_for(served_as) else {
        panic!(
            "web/{served_as} has no declared content type; \
             add one to src/content_types.rs rather than letting the server guess"
        );
    };
    let literal = file.to_str().unwrap();
    let bytes = if content_type.starts_with("text/") {
        format!("include_str!({literal:?}).as_bytes()")
    } else {
        format!("include_bytes!({literal:?})")
    };
    format!(
        "    Asset {{ path: {served_as:?}, content_type: {content_type:?}, bytes: {bytes} }},\n"
    )
}

/// Every file, plus the directories holding them. The directories are what make a file
/// that appears later rebuild the binary meant to carry it: cargo takes the recursive
/// maximum modification time under a watched directory, measured by dropping `web` from
/// this set, adding a file under `web/pkg`, and getting a binary that no longer matched
/// the directory. The files are listed as well so an edit to one is named in the log.
fn watched_paths(
    web: &Path,
    bundle: &Path,
    interface: &[PathBuf],
    bundle_files: &[PathBuf],
) -> BTreeSet<PathBuf> {
    let mut watched = BTreeSet::from([web.to_path_buf()]);
    watched.extend(interface.iter().cloned());
    if bundle.is_dir() {
        watched.insert(bundle.to_path_buf());
        watched.extend(bundle_files.iter().cloned());
    }
    watched
}
