#!/bin/sh
# Whether the help pages a reader opens are the ones the sources say.
#
# Every file under man/ carries "do not edit by hand", and nothing until now asked whether
# anybody had. No file state tells a hand-edited Rd from a generated one, so the only thing
# that settles it is a generation: roxygen runs over a copy of the package and the copy is
# compared with the tree. An edit made in man/ and not in R/ shows up here as a file that
# moved, and the next document() run in the repository would have reverted it silently.
#
# The copy is why this is safe to run anywhere: the tree is read and never written, so a
# green run and a red one leave the same working directory behind.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
package=$(dirname -- "$here")

# The alias trap `r-surface.sh` documents: the name R reaches an unrelated program on at
# least one machine here, and `Rscript` is not aliased, so the version is asked of the
# binary this script actually calls.
if ! Rscript --version 2>&1 | grep -q '^Rscript'; then
    echo "the name Rscript does not reach R here: $(command -v Rscript || echo 'not on PATH')" >&2
    exit 1
fi

# Absent roxygen is a run that cannot answer, and a run that cannot answer says so rather
# than passing. Every other outcome of this script is a comparison that happened.
if ! Rscript --vanilla -e 'quit(status = if (requireNamespace("roxygen2", quietly = TRUE)) 0 else 1)'; then
    echo "roxygen2 is not installed, so whether man/ matches R/ is unread rather than true" >&2
    exit 1
fi

# A different roxygen writes different Rd from one source, so a diff taken under one the
# package was not documented with measures the tool rather than the sources.
declared=$(sed -n 's/^RoxygenNote: *//p' "$package/DESCRIPTION" | tr -d ' \r')
installed=$(Rscript --vanilla -e 'cat(as.character(utils::packageVersion("roxygen2")))')
if [ "$declared" != "$installed" ]; then
    printf 'DESCRIPTION was written by roxygen2 %s and roxygen2 %s is installed, so this comparison would measure the difference between them\n' \
        "$declared" "$installed" >&2
    exit 1
fi

scratch=$(mktemp -d)
trap 'rm -rf "$scratch"' EXIT
cp -R "$package" "$scratch/package"
# The vendored engine's build output is the bulk of the tree and roxygen reads none of it.
rm -rf "$scratch/package/src/rust/target" "$scratch/package/src/rust/vendor"

# `load_source` rather than loading the built package: it reads R/ in the order DESCRIPTION
# collates, needs no compiled engine, and was measured to write the committed pages byte for
# byte. A loader that had to build first would make this gate answer for the build state.
Rscript --vanilla -e 'roxygen2::roxygenise(commandArgs(TRUE)[1], load_code = roxygen2::load_source)' \
    "$scratch/package" >"$scratch/roxygen.log" 2>&1 || {
    echo "roxygen could not document the package:" >&2
    cat "$scratch/roxygen.log" >&2
    exit 1
}

# Everything roxygen writes, so a stale Collate and a stale export are caught beside a stale
# help page. Each is the same defect: a generated file the sources no longer say.
moved=""
for written in man NAMESPACE DESCRIPTION; do
    if ! diff -r -q "$package/$written" "$scratch/package/$written" >"$scratch/diff.out" 2>&1; then
        moved="$moved$written
$(cat "$scratch/diff.out")
"
    fi
done

if [ -n "$moved" ]; then
    printf 'roxygen writes these differently from the tree, so a generated file was edited and the next document() run reverts it:\n%s' \
        "$moved" >&2
    exit 1
fi

# A hand-written Rd is a file roxygen leaves alone, so the comparison above cannot see one.
# The header is what tells the two apart, and every page here is generated.
unheaded=$(for page in "$package"/man/*.Rd; do
    head -1 "$page" | grep -q 'Generated by roxygen2' || printf '%s\n' "$page"
done)
if [ -n "$unheaded" ]; then
    printf 'these help pages are not generated from R/, so nothing holds their words to the sources:\n%s\n' "$unheaded" >&2
    exit 1
fi

printf '%s help pages and NAMESPACE match what roxygen2 %s writes from R/\n' \
    "$(ls "$package"/man/*.Rd | wc -l | tr -d ' ')" "$installed"
