//! Embeds the registry TOML into the binary, because a browser has no filesystem.
//!
//! The walk and the assembly are `plateforce_registry`'s own, so the browser build carries
//! the file set the desktop loader reads, and a registry the desktop refuses fails this
//! build rather than shipping.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use plateforce_registry::{assemble, read_sources, Source};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let registry_root = manifest.join("../../registry");

    let sources = read_sources(&registry_root).unwrap_or_else(|error| panic!("{error}"));
    for path in watched_paths(&registry_root, &sources) {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    assemble(sources.iter().map(Source::pair)).unwrap_or_else(|error| panic!("{error}"));

    let mut generated = String::from(
        "// Generated by build.rs. The registry travels inside the binary.\n\
         pub static EMBEDDED_REGISTRY_FILES: &[(&str, &str)] = &[\n",
    );
    for source in &sources {
        generated.push_str(&format!(
            "    ({:?}, {}),\n",
            source.path,
            raw_string_literal(&source.contents)
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_registry.rs");
    std::fs::write(out, generated).unwrap();
}

/// Every file, and every directory holding one. Without the directories, a method file
/// added to the registry would not rebuild the browser build meant to carry it.
fn watched_paths(root: &Path, sources: &[Source]) -> BTreeSet<PathBuf> {
    let mut watched = BTreeSet::from([root.to_path_buf()]);
    for source in sources {
        let file = root.join(&source.path);
        let mut ancestor = file.parent();
        while let Some(directory) = ancestor.filter(|directory| directory.starts_with(root)) {
            watched.insert(directory.to_path_buf());
            ancestor = directory.parent();
        }
        watched.insert(file);
    }
    watched
}

/// Enough `#` marks that no `"#` sequence inside a rule or a note can close the literal.
fn raw_string_literal(contents: &str) -> String {
    let mut hashes = 1;
    while contents.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let fence = "#".repeat(hashes);
    format!("r{fence}\"{contents}\"{fence}")
}
