//! Embeds the registry TOML into the binary, because a browser has no filesystem.
//!
//! The walk is by directory rather than by filename, so adding a method file stays a
//! data edit and never becomes a code edit.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let registry_root = manifest.join("../../registry");
    println!("cargo:rerun-if-changed={}", registry_root.display());

    let mut files: BTreeMap<String, String> = BTreeMap::new();
    collect(&registry_root, &registry_root, &mut files);

    let mut generated = String::from(
        "// Generated by build.rs. The registry travels inside the binary.\n\
         pub static EMBEDDED_REGISTRY_FILES: &[(&str, &str)] = &[\n",
    );
    for (relative_path, contents) in &files {
        generated.push_str(&format!(
            "    ({:?}, {}),\n",
            relative_path,
            raw_string_literal(contents)
        ));
    }
    generated.push_str("];\n\n");

    generated.push_str(&format!(
        "pub static EMBEDDED_REGISTRY_DIGEST: &str = {:?};\n",
        digest(&files)
    ));

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_registry.rs");
    std::fs::write(out, generated).unwrap();
}

fn collect(root: &Path, directory: &Path, found: &mut BTreeMap<String, String>) {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            println!("cargo:rerun-if-changed={}", path.display());
            collect(root, &path, found);
        } else if path.extension().is_some_and(|x| x == "toml") {
            println!("cargo:rerun-if-changed={}", path.display());
            let relative = path
                .strip_prefix(root)
                .unwrap_or(&path)
                .to_string_lossy()
                .replace('\\', "/");
            let text = std::fs::read_to_string(&path).unwrap();
            found.insert(relative, text);
        }
    }
}

/// Enough `#` marks that no `"#` sequence inside a rule or a note can close the literal.
fn raw_string_literal(contents: &str) -> String {
    let mut hashes = 1;
    while contents.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let fence = "#".repeat(hashes);
    format!("r{fence}\"{contents}\"{fence}")
}

/// FNV-1a over path and contents. Identifies which registry a number came from without
/// claiming to be a declared version, which the registry does not yet carry.
fn digest(files: &BTreeMap<String, String>) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for (path, contents) in files {
        for byte in path.as_bytes().iter().chain(contents.as_bytes()) {
            hash ^= u64::from(*byte);
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    format!("content-{hash:016x}")
}
