//! Embeds the registry TOML into the extension module, because a wheel installed from
//! PyPI has no clone of this repository beside it to read one from.
//!
//! The walk and the assembly are `plateforce_registry`'s own, so this build carries the
//! file set the directory loader reads, and a registry that loader refuses fails this build
//! rather than shipping.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use plateforce_registry::{assemble, read_sources, Source};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let registry_root = registry_root(&manifest);
    println!("cargo:rerun-if-changed={}", registry_root.display());

    let sources = read_sources(&registry_root).unwrap_or_else(|error| panic!("{error}"));
    for path in watched_paths(&registry_root, &sources) {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    assemble(sources.iter().map(Source::pair)).unwrap_or_else(|error| panic!("{error}"));

    let mut generated = String::from(
        "// Generated by build.rs. The registry travels inside the module.\n\
         pub static EMBEDDED_REGISTRY_FILES: &[(&str, &str)] = &[\n",
    );
    for source in &sources {
        generated.push_str(&format!(
            "    ({:?}, {}),\n",
            source.path,
            raw_string_literal(&source.contents)
        ));
    }
    generated.push_str("];\n");

    // The walk filters on the toml extension, so the revision the registry names itself is
    // not among the sources and a notebook would be the one surface unable to report it.
    let version_file = registry_root.join("VERSION");
    println!("cargo:rerun-if-changed={}", version_file.display());
    let declared = std::fs::read_to_string(&version_file)
        .ok()
        .map(|named| named.trim().to_string())
        .filter(|named| !named.is_empty());
    generated.push_str(&match declared {
        Some(version) => {
            format!("pub static EMBEDDED_REGISTRY_VERSION: Option<&str> = Some({version:?});\n")
        }
        None => "pub static EMBEDDED_REGISTRY_VERSION: Option<&str> = None;\n".to_string(),
    });

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_registry.rs");
    std::fs::write(out, generated).unwrap();
}

/// The copy inside this crate first, then the one the repository tracks.
///
/// A wheel is built from the source distribution with no checkout beside it, and the registry
/// is not a crate, so maturin carries it only when `tools/vendor-registry.sh` has put a copy
/// in here. A build in a clone finds no copy and reads the single tree every other surface
/// validates against, so nobody has to run a script to compile the crate they just cloned.
///
/// Failing names both places it looked and the command that fixes it, because this panic
/// previously read as a missing file with no indication that a copy step existed.
fn registry_root(manifest: &Path) -> PathBuf {
    let vendored = manifest.join("registry");
    if vendored.is_dir() {
        return vendored;
    }
    let tracked = manifest.join("../../registry");
    if tracked.is_dir() {
        return tracked;
    }
    panic!(
        "no registry at {} and none at {}: a source distribution carries its own copy, \
         written by crates/plateforce-python/tools/vendor-registry.sh",
        vendored.display(),
        tracked.display()
    );
}

/// Every file, and every directory holding one. Without the directories, a method file
/// added to the registry would not rebuild the module meant to carry it.
fn watched_paths(root: &Path, sources: &[Source]) -> BTreeSet<PathBuf> {
    let mut watched = BTreeSet::from([root.to_path_buf()]);
    for source in sources {
        let file = root.join(&source.path);
        let mut ancestor = file.parent();
        while let Some(directory) = ancestor.filter(|directory| directory.starts_with(root)) {
            watched.insert(directory.to_path_buf());
            ancestor = directory.parent();
        }
        watched.insert(file);
    }
    watched
}

/// Enough `#` marks that no `"#` sequence inside a rule or a note can close the literal.
fn raw_string_literal(contents: &str) -> String {
    let mut hashes = 1;
    while contents.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let fence = "#".repeat(hashes);
    format!("r{fence}\"{contents}\"{fence}")
}
