//! Embeds the registry TOML into the extension module, because a wheel installed from
//! PyPI has no clone of this repository beside it to read one from.
//!
//! The walk and the assembly are `plateforce_registry`'s own, so this build carries the
//! file set the directory loader reads, and a registry that loader refuses fails this build
//! rather than shipping.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use plateforce_registry::{assemble, read_sources, Source};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let registry_root = registry_root(&manifest);
    println!("cargo:rerun-if-changed={}", registry_root.display());

    let sources = read_sources(&registry_root).unwrap_or_else(|error| panic!("{error}"));
    for path in watched_paths(&registry_root, &sources) {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    assemble(sources.iter().map(Source::pair)).unwrap_or_else(|error| panic!("{error}"));

    let mut generated = String::from(
        "// Generated by build.rs. The registry travels inside the module.\n\
         pub static EMBEDDED_REGISTRY_FILES: &[(&str, &str)] = &[\n",
    );
    for source in &sources {
        generated.push_str(&format!(
            "    ({:?}, {}),\n",
            source.path,
            raw_string_literal(&source.contents)
        ));
    }
    generated.push_str("];\n");

    // The walk filters on the toml extension, so the revision the registry names itself is
    // not among the sources and a notebook would be the one surface unable to report it.
    let version_file = registry_root.join("VERSION");
    println!("cargo:rerun-if-changed={}", version_file.display());
    let declared = std::fs::read_to_string(&version_file)
        .ok()
        .map(|named| named.trim().to_string())
        .filter(|named| !named.is_empty());
    generated.push_str(&match declared {
        Some(version) => {
            format!("pub static EMBEDDED_REGISTRY_VERSION: Option<&str> = Some({version:?});\n")
        }
        None => "pub static EMBEDDED_REGISTRY_VERSION: Option<&str> = None;\n".to_string(),
    });

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_registry.rs");
    std::fs::write(out, generated).unwrap();
}

/// The registry beside the workspace, in a clone and inside a source distribution alike.
///
/// One path rather than two, which is the point. `tools/vendor-registry.sh` writes a copy into
/// this crate so maturin's `include` can match it, and maturin then places those files at the
/// root of the tarball, which is where this path already resolves from
/// `crates/plateforce-python`. So the copy is what gets the registry into the sdist and is not
/// what gets read out of it.
///
/// Preferring the in-crate copy was tried and reverted the same hour. It builds and it ships,
/// but it lets a copy taken before somebody edited the registry shadow the tree in every local
/// build, so the wheel embeds one registry while the repository carries another. That is the
/// drift this product exists to publish about, reproduced in our own build, and
/// `the_registry_in_the_wheel_is_the_registry_in_the_repository` caught it within minutes.
///
/// Failing names the path and the command, because this panic previously read as a missing
/// file with no indication that a copy step existed at all.
fn registry_root(manifest: &Path) -> PathBuf {
    let registry = manifest.join("../../registry");
    if registry.is_dir() {
        return registry;
    }
    panic!(
        "no registry at {}: a source distribution carries one, written into it by \
         crates/plateforce-python/tools/vendor-registry.sh before the tarball is built",
        registry.display()
    );
}

/// Every file, and every directory holding one. Without the directories, a method file
/// added to the registry would not rebuild the module meant to carry it.
fn watched_paths(root: &Path, sources: &[Source]) -> BTreeSet<PathBuf> {
    let mut watched = BTreeSet::from([root.to_path_buf()]);
    for source in sources {
        let file = root.join(&source.path);
        let mut ancestor = file.parent();
        while let Some(directory) = ancestor.filter(|directory| directory.starts_with(root)) {
            watched.insert(directory.to_path_buf());
            ancestor = directory.parent();
        }
        watched.insert(file);
    }
    watched
}

/// Enough `#` marks that no `"#` sequence inside a rule or a note can close the literal.
fn raw_string_literal(contents: &str) -> String {
    let mut hashes = 1;
    while contents.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let fence = "#".repeat(hashes);
    format!("r{fence}\"{contents}\"{fence}")
}
