#' @include measured.R analyse.R
NULL

#' The account a number gives of itself
#'
#' The value, its unit, the rule that produced it, and every rule upstream of that one with
#' the parameters each was bound to.
#'
#' The text is generated by the engine, so a number reads the same in an R session, a
#' browser tab, a terminal and a file somebody emailed on.
#'
#' @param x A `measured`, as returned by [pf_value()].
#' @param ... Unused.
#' @return `x`, invisibly. The account is printed.
#' @export
#' @examples
#' standing <- pf_trial(rep(700, 1200), sample_rate_hz = 1200)
#' result <- analyse_countermovement_jump(
#'   standing,
#'   weighing = "bwepoch.fixed_window",
#'   onset = "onset.threshold.noise_relative",
#'   takeoff = "takeoff.threshold.absolute_force"
#' )
#' describe(pf_value(result, "system_weight_newtons"))
describe <- S7::new_generic("describe", "x")

S7::method(describe, measured) <- function(x, ...) {
  cat(x@account, "\n", sep = "")
  invisible(x)
}
