/* The entry a method id opens: the rule as written, its citations, its known bias and its
 * failure rate. And the account a number gives of itself, which opens in the same panel
 * because it answers the same reader asking about the same figure. */

import { $, state } from './state.js';
import { element, formatNumber, reply, typesetUnit } from './format.js';
import { findMethod, rankCandidates } from './registry.js';
import { notice, boundValueText, ruleSourceLine, boundMethodId, buildRequest } from './analysis.js';
import { majorLandmarks } from './workspace.js';

/*
 * One number's account, as the engine wrote it.
 *
 * The text is never composed here. It arrives on the result, generated by the one site that
 * writes it, so a figure reads the same in this tab, a terminal, a notebook and an R session.
 */
export function openAccount(title, account) {
  fill(title, [accountBlock(account)]);
}

/* Every account one trial's numbers give of themselves, under the quantity each belongs to. */
export function openAccounts(title, accounts) {
  fill(
    title,
    accounts.map(([quantity, account]) => {
      const wrap = element('details', 'metric-account');
      wrap.append(element('summary', null, quantity), accountBlock(account));
      return wrap;
    }),
  );
}

/* One metric's account and every rule named in its record. */
export function openMetricRecord(metric, account, methodIds) {
  const nodes = [];
  const landmarks = landmarksBehind(methodIds);
  if (landmarks) nodes.push(landmarks);

  const competing = competingMethods(metric, methodIds);
  if (competing) nodes.push(competing);

  const section = element('section');
  section.append(element('h3', null, 'Methods'));
  const list = element('div', 'method-list');
  for (const id of [...new Set(methodIds)]) list.append(methodRecordRow(id));
  section.append(list);
  nodes.push(section);

  if (account) {
    const details = element('details', 'metric-account');
    details.append(element('summary', null, 'Calculation account'), accountBlock(account));
    nodes.push(details);
  }
  fill(metric.label, nodes, { root: true });
}

/*
 * The instants on the trace this number rests on, in the words the chart draws beside them.
 *
 * The account below spells its steps as registry ids, and a reader who cannot match
 * `onset.threshold.adaptive_trailing_window` to the label on the orange line is holding an
 * audit they cannot check against the picture in front of them. These are the same three
 * quantities the analysis reported, read off the record, so nothing here places a landmark or
 * works one out: two surfaces naming the same instant differently is the failure the ids were
 * spelt out to prevent.
 */
function landmarksBehind(methodIds) {
  if (!state.info) return null;
  const named = new Set(methodIds);
  // Only the landmarks this number's own chain reaches. A jump height that never read the
  // landing is not explained by naming where the landing was.
  const marks = majorLandmarks().filter((event) => event.rules.some((id) => named.has(id)));
  if (!marks.length) return null;

  const section = element('section');
  section.append(element('h3', null, 'On this trace'));
  const list = element('dl', 'kv kv--landmarks');
  for (const event of marks) {
    list.append(element('dt', null, event.label));
    const value = element('dd');
    value.append(element('span', 'landmark-time',
      `${(event.index / state.info.sample_rate_hz).toFixed(4)} s, sample ${event.index}`));
    value.append(element('span', 'landmark-rule', event.rules.join(', ')));
    list.append(value);
  }
  section.append(list);
  return section;
}

/*
 * The rules that would have produced this number instead, and the number each would give.
 *
 * Beside the value rather than in a panel of its own, because a reader comparing published
 * methods for one quantity is reading one thing, and the comparison used to live two surfaces
 * away from the figure it is about. The alternatives' values come from the engine running
 * them, one rule at a time against everything else the reader has settled, so a figure here
 * is a figure the software would report and not an estimate of one.
 *
 * The choices offered are the ones on this number's own chain that a reader can actually make:
 * a construct whose rule the record names behind this figure and which has more than one
 * runnable rule under it. Rooting it on the rule that computed the number instead reaches
 * nothing, because the constructs that compute quantities carry one rule each and the
 * disagreement this software exists to show lives further up, in which onset, which takeoff
 * and which weighing window.
 */
const COMPETING_RULE_CEILING = 10;

function competingMethods(metric, methodIds) {
  if (!state.loadedTrial || !state.slots) return null;
  const named = new Set(methodIds);
  const slots = state.slots.filter((slot) =>
    slot.available.length > 1 && slot.available.some((candidate) => named.has(candidate.id)));
  if (!slots.length) return null;

  const section = element('section');
  section.append(element('h3', null, 'Competing rules'));
  for (const slot of slots) {
    const ranked = rankCandidates(slot.available).slice(0, COMPETING_RULE_CEILING);
    const values = valueUnderEachRule(slot, ranked, metric);
    const running = boundMethodId(slot.key);

    section.append(element('p', 'competing__construct', slot.title));
    const list = element('div', 'competing');
    for (const candidate of ranked) {
      const isRunning = candidate.id === running;
      const row = element('div', `competing__row${isRunning ? ' competing__row--running' : ''}`);
      const name = element('button', 'competing__name');
      name.type = 'button';
      name.append(element('span', `status-dot status-dot--${candidate.status || 'legacy'}`));
      name.append(document.createTextNode(candidate.title));
      name.title = candidate.id;
      opensPanel(name, () => openDrawer(candidate.method, candidate.id, recordFor(candidate.id)));
      row.append(name);
      row.append(element('span', 'competing__mark', isRunning ? 'running' : ''));
      const answer = values.get(candidate.id);
      row.append(element(
        'span',
        'competing__value',
        answer === undefined
          ? 'no value'
          : answer === null
            ? 'no value'
            : `${formatNumber(answer, metric.unit)} ${typesetUnit(metric.unit_symbol)}`,
      ));
      list.append(row);
    }
    section.append(list);
    if (ranked.length < slot.available.length) {
      section.append(element('p', 'metric__note',
        `${ranked.length} of ${slot.available.length} rules shown.`));
    }
  }
  return section;
}

/*
 * What this quantity comes to under each of those rules, asked of the engine.
 *
 * One sweep over one axis, so every rule answers against the same settled choices the reader
 * is looking at and the difference between two rows is the rule and nothing else. A sweep
 * that declines leaves the rows without values rather than without rules: the names and their
 * citations are what the reader came for and they do not depend on a run.
 *
 * The answers are kept against the request that produced them, because opening the same panel
 * again is the same question and the reader waited for it once. The request is the key, so a
 * rule the reader has since changed can never be answered from the old run.
 */
const sweptBefore = new Map();

function valueUnderEachRule(slot, candidates, metric) {
  const answers = new Map();
  const request = JSON.stringify(buildRequest());
  const key = `${metric.key}|${slot.key}|${request}`;
  if (sweptBefore.has(key)) return sweptBefore.get(key);
  try {
    const swept = reply(state.loadedTrial.spread(JSON.stringify({
      base: JSON.parse(request),
      axes: [{
        slot: slot.key,
        parameter: null,
        values: [],
        method_ids: candidates.map((candidate) => candidate.id),
      }],
      quantity_key: metric.key,
      maximum_combinations: COMPETING_RULE_CEILING,
    })));
    if (swept.refusal) return answers;
    for (const variant of swept.ok.variants) {
      const chosen = variant.settings.find(([, value]) =>
        candidates.some((candidate) => candidate.id === value));
      // The sweep writes no setting for the combination the reader is already on, because it
      // is the one it varied away from. Its number is the baseline, and the rule it belongs
      // to is the one running, so the row for the active rule reads the same figure the card
      // reads rather than an empty cell.
      if (chosen) answers.set(chosen[1], variant.value ?? null);
      else if (swept.ok.baseline_value !== undefined) {
        answers.set(boundMethodId(slot.key), swept.ok.baseline_value ?? null);
      }
    }
  } catch {
    return answers;
  }
  // Only a sweep that answered is kept. A refused one is a question still worth asking again.
  if (answers.size) {
    if (sweptBefore.size > 64) sweptBefore.clear();
    sweptBefore.set(key, answers);
  }
  return answers;
}

function recordFor(methodId) {
  const direct = state.analysis?.bound_methods?.find((entry) => entry.method_id === methodId);
  if (direct) return direct;
  for (const row of state.analysis?.bound_methods || []) {
    const pair = (row.bound_parameters || []).find(([, value]) => value === methodId);
    if (pair) return { method_id: methodId, method_source: row.parameter_sources?.[pair[0]] };
  }
  return null;
}

function methodRecordRow(methodId) {
  const method = findMethod(state.registry, methodId);
  const bound = recordFor(methodId);
  const binding = state.build.bindings.find((entry) => entry.id === methodId);
  const backed = bound ? bound.registry_backed !== false : Boolean(method) && state.build.registry_valid;
  const button = element('button', 'provenance');
  button.type = 'button';
  if (!backed) button.classList.add('provenance--unbacked');
  button.append(element('span', `status-dot status-dot--${method?.status || 'legacy'}`));
  button.append(element('span', 'provenance__name', method?.title || binding?.title || methodId));
  const source = ruleSourceLine(bound);
  if (source) button.append(source);

  const badges = element('span', 'provenance__badges');
  if (method?.failure) {
    badges.append(element('span', 'tag tag--fails', `${(method.failure.rate * 100).toFixed(0)}% fail`));
  }
  if (bound?.manual_override) badges.append(element('span', 'tag tag--decide', 'dragged'));
  if (!backed) {
    badges.append(element('span', 'tag tag--advanced', binding?.composed_from ? 'composed' : 'unfiled'));
  }
  if (badges.childElementCount) button.append(badges);
  button.title = methodId;
  opensPanel(button, () => openDrawer(method, methodId, bound));
  return button;
}

/* Each step's distance from the number is written in leading spaces, so the block keeps them
 * rather than reflowing a rule that fed another rule to the depth of the one it fed. */
function accountBlock(account) {
  return element('pre', 'rule-text account', account);
}

function fill(title, nodes, { root = false } = {}) {
  if (root) returnView = null;
  $('drawer-back').hidden = true;
  $('drawer-title').textContent = title;
  $('drawer-body').replaceChildren(...nodes);
  showPanel($('method-drawer'));
}

/* The control the panel was opened from, so closing puts the reader back on it. */
let openedFrom = null;
let returnView = null;

/*
 * A control that opens a panel, taking the focus its own press is owed.
 *
 * Where the reader came from is read off `document.activeElement`, and a press does not put it
 * there everywhere: WebKit leaves a button unfocused when it is clicked, so on macOS closing a
 * rule detail returned the reader to whatever held focus before they reached the row. The same
 * fact that kept the keyboard off the chart landmarks.
 */
export function opensPanel(button, open) {
  button.addEventListener('click', () => {
    button.focus();
    open();
  });
  return button;
}

/*
 * A panel that covers the screen takes the keyboard with it.
 *
 * These panels declare themselves modal, so a reader working from the keyboard belongs
 * inside one while it is open. Focus left behind the scrim walks the page the panel is
 * covering, on the drawer a reader opens to read what a rule is.
 */
export function showPanel(drawer) {
  if (drawer.hidden) openedFrom = document.activeElement;
  drawer.hidden = false;
  focusableWithin(drawer).find((entry) => !entry.matches('[data-close-drawer]'))?.focus();
}

export function hidePanel(drawer) {
  drawer.hidden = true;
  returnView = null;
  $('drawer-back').hidden = true;
  openedFrom?.focus?.();
  openedFrom = null;
}

export function returnInDrawer() {
  if (!returnView) return;
  const held = returnView;
  returnView = null;
  $('drawer-title').textContent = held.title;
  $('drawer-body').replaceChildren(...held.nodes);
  $('drawer-back').hidden = true;
  window.setTimeout(() => held.focus?.focus?.(), 0);
}

export function focusableWithin(node) {
  return [...node.querySelectorAll('a[href], button, input, select, textarea, [tabindex]:not([tabindex="-1"])')]
    .filter((entry) => !entry.disabled && entry.offsetParent !== null);
}

export function openDrawer(method, fallbackId, bound) {
  const drawer = $('method-drawer');
  const body = $('drawer-body');
  if (!drawer.hidden && body.childElementCount && !returnView) {
    returnView = {
      title: $('drawer-title').textContent,
      nodes: [...body.childNodes],
      focus: document.activeElement,
    };
  }
  $('drawer-back').hidden = !returnView;
  body.replaceChildren();
  $('drawer-title').textContent =
    method?.title || state.build.bindings.find((entry) => entry.id === fallbackId)?.title || fallbackId;

  // Ahead of everything the entry says about itself, because a reader who has just opened a
  // where the panel was opened from the registry rather than from a result, which carries no
  // claim about any run.
  const chosen = ruleSourceLine(bound);
  if (chosen) body.append(chosen);

  if (!method) {
    const binding = state.build.bindings.find((entry) => entry.id === fallbackId);
    if (binding?.composed_from) {
      const base = findMethod(state.registry, binding.composed_from);
      body.append(
        notice(
          'warning',
          'Composition',
          `Uses ${binding.composed_from} and its citations.`,
        ),
      );
      if (base) {
        const open = element('button', 'button button--ghost button--small', 'Open source entry');
        open.type = 'button';
        opensPanel(open, () => openDrawer(base));
        body.append(open);
      }
    } else {
      body.append(
        notice(
          'warning',
          'Not a registry entry',
          'No citation, bias, or failure rate.',
        ),
      );
    }
    showPanel(drawer);
    return;
  }

  const section = (heading, node) => {
    const wrap = element('section');
    wrap.append(element('h3', null, heading));
    wrap.append(node);
    return wrap;
  };

  const identity = element('dl', 'kv');
  const rows = [
    ['Registry id', method.id],
    ['Construct', method.construct],
    ['Status', method.status],
    ['Confidence', method.confidence],
    ['Debate', method.debate || 'not stated'],
  ];
  if (bound?.bound_parameters?.length) {
    rows.push(['Bound here', boundValueText(bound, ' = ').join(', ')]);
  }
  if (bound?.unread_parameters?.length) {
    rows.push(['Not taken by this rule', bound.unread_parameters.join(', ')]);
  }
  for (const [term, definition] of rows) identity.append(element('dt', null, term), element('dd', null, definition));
  body.append(section('Entry', identity));

  body.append(section('Rule', element('p', 'rule-text', method.rule.trim())));

  if (method.failure) {
    body.append(
      section(
        'Failure rate',
        notice(
          'danger',
          `${(method.failure.rate * 100).toFixed(1)} percent, ${method.failure.numerator} of ${method.failure.denominator}`,
          `${method.failure.definition}. Corpus: ${method.failure.corpus}. Detectability: ${method.failure.detectability}.`,
        ),
      ),
    );
  }

  if (method.parameter?.length) {
    const list = element('ul');
    for (const parameter of method.parameter) {
      const item = element('li');
      item.append(element('strong', null, parameter.name));
      const published = parameter.published_values?.length ? ` Published values: ${parameter.published_values.join(', ')}.` : '';
      const chosen = parameter.default != null ? ` Default ${parameter.default} from ${parameter.default_source || 'an unnamed source'}.` : '';
      item.append(document.createTextNode(`${parameter.unit ? ` (${parameter.unit})` : ''}.${published}${chosen}`));
      if (parameter.notes) item.append(element('p', 'metric__note', parameter.notes.trim()));
      list.append(item);
    }
    body.append(section('Parameters', list));
  }

  if (method.citation?.length) {
    const list = element('ul');
    for (const citation of method.citation) {
      const item = element('li');
      item.append(element('strong', null, `${citation.role}: `));
      item.append(document.createTextNode(citation.reference));
      if (citation.doi) {
        const link = element('a', null, ` doi:${citation.doi}`);
        link.href = `https://doi.org/${citation.doi}`;
        link.rel = 'noreferrer';
        link.target = '_blank';
        item.append(link);
      }
      if (!citation.obtained) item.append(element('span', 'tag tag--decide', 'source not obtained'));
      list.append(item);
    }
    body.append(section('Citations', list));
  }

  if (method.bias?.length) {
    const list = element('ul');
    for (const bias of method.bias) {
      list.append(
        element(
          'li',
          null,
          `${bias.magnitude} ${bias.unit}${bias.direction ? ` (${bias.direction})` : ''} against ${bias.criterion} (${bias.criterion_kind})` +
            `${bias.source ? `, reported by ${bias.source}` : ''}${bias.conditional_on_success ? '. Conditional on the rule having worked.' : ''}`,
        ),
      );
    }
    body.append(section('Known bias', list));
  }

  if (method.disagrees_with?.length) {
    const list = element('ul');
    for (const other of method.disagrees_with) {
      const item = element('li', null, `${other.id} (${other.kind})`);
      // A reader choosing between two rules is choosing between two sources, and the id
      // alone does not say whose the other one is.
      const alternative = findMethod(state.registry, other.id);
      const source = alternative?.citation?.[0];
      if (source) {
        item.append(document.createTextNode(`, ${source.role}: ${source.reference}`));
      }
      if (other.note) item.append(document.createTextNode(`. ${other.note}`));
      if (alternative) {
        const open = element('button', 'button button--ghost button--small', 'Open this entry');
        open.type = 'button';
        opensPanel(open, () => openDrawer(alternative));
        item.append(document.createTextNode(' '));
        item.append(open);
      }
      list.append(item);
    }
    body.append(section('Disagrees with', list));
  }

  showPanel(drawer);
}
